services:
  tModLoader:
    build: .
    image: localhost/tmodloader
    volumes:
      # - ./Mods:/root/.local/share/Terraria/tModLoader/Mods
      - ./Worlds:/root/.local/share/Terraria/tModLoader/Worlds
      - ./serverconfig.txt:/root/terraria-server/serverconfig.txt
      - ./install.txt:/root/terraria-server/install.txt
      - ./enabled.json:/root/.local/share/Terraria/tModLoader/Mods/enabled.json
    ports:
      - "7777:7777"
    
    # stdin_open: true
    # tty: true
